---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv1
  labels:
    type: kafka
spec:
  storageClassName: kafka
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/kafka_data1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv2
  labels:
    type: kafka
spec:
  storageClassName: kafka
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/kafka_data2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv3
  labels:
    type: kafka
spec:
  storageClassName: kafka
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/kafka_data3"